Repository Team-UniVoice/UniVoice_iOS, pull requests merged in 2024-07, with the labels that each got.

#4 [Setting/#3] Color setting
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Global/Extension/UIColor+.swift
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/Font/B01.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/Font/B02.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/Font/B03.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/Font/B04.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/Font/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/Font/W01.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/Line/Black.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/Line/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/Line/Light.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/Line/Regular.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Blue100.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Blue200.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Blue300.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Blue400.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Blue50.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Blue500.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Blue600.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Blue700.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Blue800.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Blue900.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Gray100.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Gray200.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Gray300.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Gray400.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Gray50.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Gray500.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Gray600.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Gray700.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Gray800.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Gray900.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Mint100.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Mint200.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Mint300.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Mint400.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Mint50.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Mint500.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Mint600.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Mint700.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Mint800.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Mint900.colorset/Contents.json
Labels: ⚙️ Setting

#9 [Setting/#8] 프로젝트 CICD 세팅
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: ⚙️ Setting

#10 [Setting/#7] 폰트 세팅
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Global/Extension/NSAttributedString+.swift
  UniVoice/UniVoice/Global/Extension/UIButton+.swift
  UniVoice/UniVoice/Global/Extension/UIFont+.swift
  UniVoice/UniVoice/Global/Extension/UILabel+.swift
  UniVoice/UniVoice/Global/Literal/Font/Pretendard-Black.otf
  UniVoice/UniVoice/Global/Literal/Font/Pretendard-Bold.otf
  UniVoice/UniVoice/Global/Literal/Font/Pretendard-ExtraBold.otf
  UniVoice/UniVoice/Global/Literal/Font/Pretendard-ExtraLight.otf
  UniVoice/UniVoice/Global/Literal/Font/Pretendard-Light.otf
  UniVoice/UniVoice/Global/Literal/Font/Pretendard-Medium.otf
  UniVoice/UniVoice/Global/Literal/Font/Pretendard-Regular.otf
  UniVoice/UniVoice/Global/Literal/Font/Pretendard-SemiBold.otf
  UniVoice/UniVoice/Global/Literal/Font/Pretendard-Thin.otf
  UniVoice/UniVoice/Global/Utility/Info.plist
Labels: ⚙️ Setting

#14 [Setting/#8] temp app icon 추가
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/AppIcon.appiconset/uniVoiceAppIcon.png
Labels: ⚙️ Setting

#18 [Setting/#17] ViewModel 폴더 생성
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/StudentIDPhotoInputVM.swift
Labels: ⚙️ Setting

#15 [Design/#13] LoginPage Refine, Common UI Setting
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Application/SceneDelegate.swift
  UniVoice/UniVoice/Global/Extension/UINavigationBar+.swift
  UniVoice/UniVoice/Global/Extension/UITextField+.swift
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_back.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_back.imageset/icn_back.svg
  UniVoice/UniVoice/Global/Utility/PreviewController.swift
  UniVoice/UniVoice/Presentation/Components/CustomButton.swift
  UniVoice/UniVoice/Presentation/Components/CustomTextfield.swift
  UniVoice/UniVoice/Presentation/LoginPage/View/InitialView.swift
  UniVoice/UniVoice/Presentation/LoginPage/View/LoginView.swift
  UniVoice/UniVoice/Presentation/LoginPage/View/WelcomeView.swift
  UniVoice/UniVoice/Presentation/LoginPage/ViewController/LoginViewController.swift
Labels: ✨ Feat, 🎨 Design

#23 [Chore/#22] Custom Component Maintenance
  UniVoice/UniVoice/Presentation/Components/CustomButton.swift
  UniVoice/UniVoice/Presentation/Components/CustomTextfield.swift
Labels: 🧹 Chore

#27 [Feat/#20] 회원가입 UI View 구현 (학생증 사진 업로드 이후 부분)
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_forward.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_forward.imageset/icn_forward.svg
  UniVoice/UniVoice/Presentation/SignUpPage/View/CreateAccountView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/SignUpInfoCheckingView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/StudentIDPhotoInputView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/StudentInfoConfirmView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/StudentInfoInputView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/TOSCheckView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/CreateAccountVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/SignUpInfoCheckingVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/StudentIDPhotoInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/StudentInfoConfirmVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/StudentInfoInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/TOSCheckVC.swift
Labels: ✨ Feat

#29 Feat/#21 sign up page part1
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_polygon_down.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_polygon_down.imageset/icn_polygon_down 1.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_polygon_down.imageset/icn_polygon_down 2.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_polygon_down.imageset/icn_polygon_down.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_polygon_up.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_polygon_up.imageset/icn_polygon_up 1.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_polygon_up.imageset/icn_polygon_up 2.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_polygon_up.imageset/icn_polygon_up.svg
  UniVoice/UniVoice/Presentation/SignUpPage/View/AdmissionYearSelectionView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/DepartmentInputView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/SignUpIntroView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/UnivInfoConfirmView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/UniversityInputView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/UniversityTableViewCell.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/AdmissionYearSelectionVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/DepartmentInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/SignUpIntroVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/UniversityInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/UniversityInputVM.swift
Labels: ✨ Feat

#24 [Feat/#19] Main home UI (~Quick Scan)
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UniVoice/UniVoice/Domain/MainHomeModel/mainHomeModel.swift
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/defaultImage.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/defaultImage.imageset/Rectangle 2862019.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/mainLogo.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/mainLogo.imageset/Group 1707481233.svg
  UniVoice/UniVoice/Presentation/MainHome/View/ArticleHeaderView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/QuickScanCollectionViewCell.swift
  UniVoice/UniVoice/Presentation/MainHome/View/MainHomeView.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/MainHomeViewController.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewModel/QuickScanViewModel.swift
Labels: ✨ Feat

#33 [Feat/#28] 학생증 인증 비즈니스 로직 구현
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Application/SceneDelegate.swift
  UniVoice/UniVoice/Global/Extension/UIImage+.swift
  UniVoice/UniVoice/Global/Utility/Info.plist
  UniVoice/UniVoice/Presentation/SignUpPage/View/StudentIDPhotoInputView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/StudentInfoConfirmView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/StudentInfoInputView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/StudentIDPhotoInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/StudentInfoConfirmVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/StudentInfoInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/StudentIDPhotoInputVM.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/StudentInfoConfirmVM.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/StudentInfoInputVM.swift
Labels: ✨ Feat

#35 Feat/#25 main home UI **merge를 위한 중간점검용 PR입니다
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Domain/MainHomeModel/mainHomeModel.swift
  UniVoice/UniVoice/Presentation/Components/CustomButton.swift
  UniVoice/UniVoice/Presentation/MainHome/View/ArticleHeaderView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/ArticleCVC.swift
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/CouncilCVC.swift
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/QuickScanCollectionViewCell.swift
  UniVoice/UniVoice/Presentation/MainHome/View/MainHomeView.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/MainHomeViewController.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewModel/MainHomeViewModel.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewModel/QuickScanViewModel.swift
Labels: ✨ Feat

#41 [Feat/#16] QuickScanPage 작성 - Updated
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Domain/QuickScan/QuickScan.swift
  UniVoice/UniVoice/Global/Extension/Date+.swift
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_bookmark_off.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_bookmark_off.imageset/icn_bookmark_off.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_bookmark_on.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_bookmark_on.imageset/icn_bookmark_on.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_defaultProfile.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_defaultProfile.imageset/icn_defaultProfile.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_viewCount.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_viewCount.imageset/icn_viewCount.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/img_happyUniv.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/img_happyUniv.imageset/img_happyUniv.svg
  UniVoice/UniVoice/Global/Utility/Info.plist
  UniVoice/UniVoice/Presentation/Components/CapsuleLabelView.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/View/Cell/QuickScanContentCollectionViewCell.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/View/ChipContentView.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/View/QuickScanCompletionView.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/View/QuickScanIndicatorView.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/View/QuickScanView.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/ViewController/QuickScanCompletionViewController.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/ViewController/QuickScanViewController.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/ViewModel/QuickScanViewModel.swift
Labels: ✨ Feat

#42 [Chore/#22] CustomTextField 밑줄 UI 수정
  UniVoice/UniVoice/Presentation/Components/CustomTextfield.swift
Labels: 🧹 Chore, 🎨 Design

#40 [Feat/#34] 계정 생성, 약관동의 비즈니스 로직 구현
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Application/SceneDelegate.swift
  UniVoice/UniVoice/Global/Extension/Reactive+.swift
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/ColorSet/System/Red0.colorset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_checkedBox.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_checkedBox.imageset/Property 1=checkbox_on.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_uncheckedBox.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_uncheckedBox.imageset/Property 1=checkbox_off.svg
  UniVoice/UniVoice/Presentation/SignUpPage/View/CreateAccountView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/TOSCheckView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/CreateAccountVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/TOSCheckVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/CreateAccountVM.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/TOSCheckVM.swift
Labels: ✨ Feat

#44 [Refactor/#43] 코드리뷰 반영
  UniVoice/UniVoice/Global/Extension/Reactive+.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/CreateAccountVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/TOSCheckVM.swift
Labels: 🛠️ Refactor

#47 [Add/#45] 폰트 변경사항 반영
  UniVoice/UniVoice/Global/Extension/NSAttributedString+.swift
  UniVoice/UniVoice/Global/Extension/UIFont+.swift
Labels: 🔥 Add

#49 [Feat/#46] LoginPage Refine, LoginFailCase 추가
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Application/SceneDelegate.swift
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/img_welcomeUniv.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/img_welcomeUniv.imageset/img_welcomeUniv.svg
  UniVoice/UniVoice/Presentation/LoginPage/View/InitialView.swift
  UniVoice/UniVoice/Presentation/LoginPage/View/LoginView.swift
  UniVoice/UniVoice/Presentation/LoginPage/View/NoAccountView.swift
  UniVoice/UniVoice/Presentation/LoginPage/View/WelcomeView.swift
  UniVoice/UniVoice/Presentation/LoginPage/ViewController/LoginViewController.swift
  UniVoice/UniVoice/Presentation/LoginPage/ViewController/NoAccountViewController.swift
Labels: ✨ Feat, 🎨 Design

#51 [Feat/#26] TabBar 구현
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/home_filled_ic.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/home_filled_ic.imageset/icn_nav-1.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/home_ic.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/home_ic.imageset/icn_nav.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/mypage_filled_ic.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/mypage_filled_ic.imageset/icn_nav.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/mypage_ic.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/mypage_ic.imageset/icn_nav-2.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/save_filled_ic.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/save_filled_ic.imageset/icn_nav-2.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/save_ic.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/save_ic.imageset/icn_nav-1.svg
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/CouncilCVC.swift
  UniVoice/UniVoice/Presentation/MainHome/View/HeaderView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/MainHomeView.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/MainHomeViewController.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewModel/MainHomeViewModel.swift
  UniVoice/UniVoice/Presentation/TabBar/Model/AppTab.swift
  UniVoice/UniVoice/Presentation/TabBar/TabBarVC.swift
Labels: ✨ Feat

#52 [Feat/#48] TextField 입력에 따른 Button 로직 구현
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/StudentInfoInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/StudentInfoInputVM.swift
Labels: ✨ Feat

#53 [Feat/#25] main home UI
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_like.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_like.imageset/icn_heart.svg
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/ArticleCVC.swift
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/QuickScanCollectionViewCell.swift
  UniVoice/UniVoice/Presentation/MainHome/View/MainHomeView.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/MainHomeViewController.swift
  UniVoice/UniVoice/Presentation/TabBar/TabBarVC.swift
Labels: ✨ Feat, 🎨 Design

#55 [Feat/#37] create notice UI, 비즈니스 로직
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Global/Extension/Date+.swift
  UniVoice/UniVoice/Global/Extension/UIView+.swift
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/btn_wrt_delete.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/btn_wrt_delete.imageset/btn_wrt_delete_.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_camera.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_camera.imageset/icn_camera_16.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_cdr.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_cdr.imageset/icn_cdr_16.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_delete.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_delete.imageset/icn_delete.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_next.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_next.imageset/icn_next.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_people.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_people.imageset/icn_people_16.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test1.imageset/1.jpeg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test1.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test2.imageset/2.jpeg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test2.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test3.imageset/3.jpg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test3.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test4.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test4.imageset/스크린샷 2024-03-10 오전 6.12.32.png
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test5.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test5.imageset/IMG_2154.HEIC
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test6.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/test7.imageset/Contents.json
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/ImageCVC.swift
  UniVoice/UniVoice/Presentation/MainHome/View/CreateNoticeView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/DateView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/TargetView.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/CreateNoticeVC.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewModel/CreateNoticeVM.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/AdmissionYearSelectionView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/Cell/DepartmentTableViewCell.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/Cell/UniversityTableViewCell.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/DepartmentInputView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/DepartmentTableViewCell.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/SignUpIntroView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/UnivInfoConfirmView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/UniversityInputView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/UniversityTableViewCell.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/DepartmentInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/UniversityInputVC.swift
Labels: ✨ Feat

#54 [Refactor/#50] 전반적인 프로젝트 화면 흐름 조정
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/img_checkUniv.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/img_checkUniv.imageset/img_checkUniv.svg
  UniVoice/UniVoice/Presentation/LoginPage/ViewController/InitialViewController.swift
  UniVoice/UniVoice/Presentation/LoginPage/ViewController/WelcomeViewController.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/CreateAccountView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/SignUpInfoCheckingView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/StudentIDPhotoInputView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/StudentInfoConfirmView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/SignUpInfoCheckingVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/UnivInfoConfirmVC.swift
Labels: 🛠️ Refactor

#61 [Refactor/#50] 프로젝트 플로우 연결 2차 작업
  UniVoice/UniVoice/Presentation/LoginPage/ViewController/WelcomeViewController.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/MainHomeViewController.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/ViewController/QuickScanCompletionViewController.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/ViewController/QuickScanViewController.swift
  UniVoice/UniVoice/Presentation/TabBar/TabBarVC.swift
Labels: 🛠️ Refactor

#62 [Feat/#58] 계정 생성View 로직 추가
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/CreateAccountVC.swift
Labels: ✨ Feat

#63 [Feat/#56] create notice page
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Global/Extension/UIView+.swift
  UniVoice/UniVoice/Presentation/Components/CustomTextfield.swift
  UniVoice/UniVoice/Presentation/MainHome/View/CreateNoticeView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/DateInputView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/TargetInputView.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/CreateNoticeVC.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewModel/CreateNoticeVM.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/AdmissionYearSelectionVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/UniversityInputVC.swift
Labels: ✨ Feat

#68 [Feat/#64] create notice page
  UniVoice/UniVoice/Presentation/MainHome/View/CreateNoticeView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/DateInputView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/DateView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/TargetInputView.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/CreateNoticeVC.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewModel/CreateNoticeVM.swift
Labels: ✨ Feat

#73 [Feat/#72] API 구조 설계 및 초기 세팅
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Data/Router/MoyaLoggingPlugin.swift
  UniVoice/UniVoice/Data/Router/NetworkResult.swift
  UniVoice/UniVoice/Data/Router/Service/NoticeService.swift
  UniVoice/UniVoice/Data/Router/Service/Service.swift
  UniVoice/UniVoice/Data/Router/Service/ServiceManager.swift
  UniVoice/UniVoice/Data/Router/Service/UserService.swift
  UniVoice/UniVoice/Data/Router/TargetType/NoticeTargetType.swift
  UniVoice/UniVoice/Data/Router/TargetType/UniVoiceTargetType.swift
  UniVoice/UniVoice/Data/Router/TargetType/UserTargetType.swift
Labels: ✨ Feat

#70 [Feat/#69] CreateNoticeView 로직 작성
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/ImageCVC.swift
  UniVoice/UniVoice/Presentation/MainHome/View/CreateNoticeView.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/CreateNoticeVC.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewModel/CreateNoticeVM.swift
Labels: ✨ Feat

#79 [Feat/#38] detail notice UI
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Domain/DetailNotice/DetailNotice.swift
  UniVoice/UniVoice/Global/Extension/Date+.swift
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_like_off.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_like_off.imageset/icn_heart_Status=off.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_like_on.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/IconSet/icn_like_on.imageset/icn_heart_Status=on.svg
  UniVoice/UniVoice/Presentation/DetailNotice/View/Cell/NoticeImageCVC.swift
  UniVoice/UniVoice/Presentation/DetailNotice/View/DetailNoticeView.swift
  UniVoice/UniVoice/Presentation/DetailNotice/ViewController/DetailNoticeVC.swift
  UniVoice/UniVoice/Presentation/DetailNotice/ViewModel/DetailNoticeVM.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/ViewModel/QuickScanViewModel.swift
Labels: ✨ Feat

#81 [Refactor/#76] detail notice 화면연결
  UniVoice/UniVoice/Presentation/MainHome/ViewController/MainHomeViewController.swift
Labels: 🛠️ Refactor

#82 [Design/#78] main home UI design
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/mypage_filled_ic.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/mypage_filled_ic.imageset/icn_nav.png
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/mypage_filled_ic.imageset/icn_nav.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/mypage_ic.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/mypage_ic.imageset/Property 2=icn_setting, Property 3=off.png
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/TabBarIcon/mypage_ic.imageset/icn_nav-2.svg
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/ArticleCVC.swift
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/CouncilCVC.swift
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/QuickScanCollectionViewCell.swift
  UniVoice/UniVoice/Presentation/MainHome/View/HeaderView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/MainHomeView.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/MainHomeViewController.swift
Labels: 🎨 Design

#85 [Feat/#71] CreateNoticePage target, date 수정/삭제 로직 작성
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Global/Extension/Date+.swift
  UniVoice/UniVoice/Presentation/MainHome/View/CreateNoticeView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/DateInputView.swift
  UniVoice/UniVoice/Presentation/MainHome/View/UploadingNoticeView.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/CreateNoticeVC.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/UploadingNoticeVC.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewModel/CreateNoticeVM.swift
Labels: ✨ Feat

#84 [Feat/#80] API 세팅 및 구현
  .gitignore
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Data/Base/BaseResponse.swift
  UniVoice/UniVoice/Data/Router/Config.swift
  UniVoice/UniVoice/Data/Router/MoyaLoggingPlugin.swift
  UniVoice/UniVoice/Data/Router/NetworkError.swift
  UniVoice/UniVoice/Data/Router/Plugin/AccessTokenPlugin.swift
  UniVoice/UniVoice/Data/Router/Plugin/MoyaLoginPlugin.swift
  UniVoice/UniVoice/Data/Router/RequestModel/IDCheckRequest.swift
  UniVoice/UniVoice/Data/Router/RequestModel/LoginRequest.swift
  UniVoice/UniVoice/Data/Router/RequestModel/UniversityNameRequest.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/LoginResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/UniversityDataResponse.swift
  UniVoice/UniVoice/Data/Router/Service/NoticeService.swift
  UniVoice/UniVoice/Data/Router/Service/Service.swift
  UniVoice/UniVoice/Data/Router/Service/ServiceManager.swift
  UniVoice/UniVoice/Data/Router/Service/UserService.swift
  UniVoice/UniVoice/Data/Router/TargetType/UserTargetType.swift
  UniVoice/UniVoice/Global/Utility/Info.plist
  UniVoice/UniVoice/Global/Utility/KeyChain.swift
Labels: ✨ Feat

#87 [Feat/#86] NoticeService API 구현
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Data/Router/RequestModel/UnreadQuickScanRequest.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/AllNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/CollegeStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/DepartmentStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/MainStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/MyPageResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/NoticeDetailResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/QuickScanStoryResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/SavedNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/UnreadQuickScanListResponse.swift
  UniVoice/UniVoice/Data/Router/Service/NoticeService.swift
  UniVoice/UniVoice/Data/Router/TargetType/NoticeTargetType.swift
Labels: ✨ Feat

#91 [Feat/#83] my page UI
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/profile_image.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/profile_image.imageset/Group 1707481426.svg
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/school_image.imageset/Contents.json
  UniVoice/UniVoice/Global/Resource/Assets.xcassets/school_image.imageset/Ellipse 5355.svg
  UniVoice/UniVoice/Presentation/DetailNotice/ViewController/DetailNoticeVC.swift
  UniVoice/UniVoice/Presentation/MyPage/View/MyPageSelectView.swift
  UniVoice/UniVoice/Presentation/MyPage/View/MyPageView.swift
  UniVoice/UniVoice/Presentation/MyPage/ViewController/MyPageVC.swift
Labels: ✨ Feat

#93 [Feat/#89] 로그인 api 로직 작성
  UniVoice/UniVoice/Presentation/LoginPage/ViewModel/LoginViewModel.swift
Labels: ✨ Feat

#96 Feat/#90 회원가입 (학생증 전) 플로우 API 연결
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UniVoice/UniVoice/Global/Resource/finsh motion(ios).json
  UniVoice/UniVoice/Global/Resource/loading(ios).json
  UniVoice/UniVoice/Presentation/MainHome/View/UploadingNoticeView.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/CreateNoticeVC.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/UploadingNoticeVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/DepartmentInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/UniversityInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/DepartmentInputVM.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/UniversityInputVM.swift
Labels: ✨ Feat

#97 [Feat/#88] UserService 회원가입 요청 API 구현 및 연결, 중복확인 API 연결
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Data/Router/RequestModel/SignUpRequest.swift
  UniVoice/UniVoice/Data/Router/Service/Service.swift
  UniVoice/UniVoice/Data/Router/Service/UserService.swift
  UniVoice/UniVoice/Data/Router/TargetType/UserTargetType.swift
  UniVoice/UniVoice/Domain/SignUpDataManager.swift
  UniVoice/UniVoice/Global/Extension/Data+.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/CreateAccountVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/TOSCheckVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/CreateAccountVM.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/StudentIDPhotoInputVM.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/StudentInfoInputVM.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/TOSCheckVM.swift
Labels: ✨ Feat

#98 [Feat/#94] QuickScan 페이지 API 연결
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Data/Router/Plugin/MoyaLoggerPlugin.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/UnreadQuickScanListResponse.swift
  UniVoice/UniVoice/Data/Router/Service/ServiceManager.swift
  UniVoice/UniVoice/Domain/MainHomeModel/mainHomeModel.swift
  UniVoice/UniVoice/Global/Extension/String+.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/MainHomeViewController.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/ViewController/QuickScanViewController.swift
  UniVoice/UniVoice/Presentation/QuickScanPage/ViewModel/QuickScanViewModel.swift
Labels: ✨ Feat

#99 [Feat/#92] main home api
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Data/Router/ResponseModel/AllNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/CollegeStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/DepartmentStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/MainStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/QuickScanStoryResponse.swift
  UniVoice/UniVoice/Domain/MainHomeModel/mainHomeModel.swift
  UniVoice/UniVoice/Global/Extension/String+.swift
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/ArticleCVC.swift
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/CouncilCVC.swift
  UniVoice/UniVoice/Presentation/MainHome/View/Cell/QuickScanCollectionViewCell.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/MainHomeViewController.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewModel/MainHomeViewModel.swift
  UniVoice/UniVoice/Presentation/SavePage/ViewModel/SavedNoticeVM.swift
Labels: ✨ Feat

#102 [Setting/#101] ci_post_clone.sh 추가
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/ci_scripts/ci_post_clone.sh
Labels: ⚙️ Setting

#103 [Setting/#101] CICD 세팅 2트
  UniVoice/ci_scripts/ci_post_clone.sh
Labels: ⚙️ Setting

#108 [Feat/#100] 세부 공지사항 API 연결
  UniVoice/UniVoice/Data/Router/ResponseModel/AllNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/CollegeStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/DepartmentStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Data/Router/ResponseModel/MainStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Domain/MainHomeModel/mainHomeModel.swift
  UniVoice/UniVoice/Presentation/DetailNotice/View/DetailNoticeView.swift
  UniVoice/UniVoice/Presentation/DetailNotice/ViewController/DetailNoticeVC.swift
  UniVoice/UniVoice/Presentation/DetailNotice/ViewModel/DetailNoticeVM.swift
  UniVoice/UniVoice/Presentation/MainHome/ViewController/MainHomeViewController.swift
Labels: ✨ Feat

#111 [Feat/#109] 저장, 마이 페이지 API 구현
  UniVoice/UniVoice/Data/Router/ResponseModel/SavedNoticeListResponse.swift
  UniVoice/UniVoice/Presentation/MyPage/View/MyPageView.swift
  UniVoice/UniVoice/Presentation/MyPage/ViewController/MyPageVC.swift
  UniVoice/UniVoice/Presentation/SavePage/ViewController/SavedNoticeVC.swift
  UniVoice/UniVoice/Presentation/SavePage/ViewModel/SavedNoticeVM.swift
Labels: ✨ Feat

#114 [Feat/#113] 학교, 학과, 학번 데이터 바인딩
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/AdmissionYearSelectionVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/DepartmentInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/UniversityInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/AdmissionYearSelectionVM.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/DepartmentInputVM.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/UniversityInputVM.swift
Labels: ✨ Feat

#118 [Feat/#117] UI 수정 사항 반영
  UniVoice/UniVoice/Presentation/MainHome/View/DateInputView.swift
Labels: ✨ Feat, 🎨 Design

#136 [Feat/#135] 회원가입 이용약관 링크 연결 및 QA 반영
  UniVoice/UniVoice.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UniVoice/UniVoice/Presentation/SignUpPage/View/CreateAccountView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/View/TOSCheckView.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/TOSCheckVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/CreateAccountVM.swift
Labels: ✨ Feat, 🐞 Fix, 🎨 Design

#141 [Fix/#139] QA 반영
  UniVoice/UniVoice/Global/Extension/UIViewController+.swift
  UniVoice/UniVoice/Presentation/LoginPage/ViewController/LoginViewController.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/CreateAccountVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/DepartmentInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/StudentInfoInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/UniversityInputVC.swift
Labels: 🐞 Fix

#146 [Docs] README 업데이트
  README.md
Labels: 📚 Docs

#150 [Fix #148] QA 반영
  UniVoice/UniVoice/Presentation/LoginPage/View/InitialView.swift
  UniVoice/UniVoice/Presentation/LoginPage/ViewController/LoginViewController.swift
  UniVoice/UniVoice/Presentation/LoginPage/ViewModel/LoginViewModel.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/CreateAccountVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewController/StudentInfoInputVC.swift
  UniVoice/UniVoice/Presentation/SignUpPage/ViewModel/StudentInfoInputVM.swift
Labels: 🐞 Fix

#152 [Docs/#151] README 수정
  README.md
Labels: 📚 Docs

#155 [Chore/#154] 폴더 위치 변경
  UniVoice/UniVoice.xcodeproj/project.pbxproj
  UniVoice/UniVoice/Data/DTO/RequestModel/IDCheckRequest.swift
  UniVoice/UniVoice/Data/DTO/RequestModel/LoginRequest.swift
  UniVoice/UniVoice/Data/DTO/RequestModel/PostNoticeRequest.swift
  UniVoice/UniVoice/Data/DTO/RequestModel/SignUpRequest.swift
  UniVoice/UniVoice/Data/DTO/RequestModel/UniversityNameRequest.swift
  UniVoice/UniVoice/Data/DTO/RequestModel/UnreadQuickScanRequest.swift
  UniVoice/UniVoice/Data/DTO/ResponseModel/AllNoticeListResponse.swift
  UniVoice/UniVoice/Data/DTO/ResponseModel/CollegeStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Data/DTO/ResponseModel/DepartmentStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Data/DTO/ResponseModel/LoginResponse.swift
  UniVoice/UniVoice/Data/DTO/ResponseModel/MainStudentCouncilNoticeListResponse.swift
  UniVoice/UniVoice/Data/DTO/ResponseModel/MyPageResponse.swift
  UniVoice/UniVoice/Data/DTO/ResponseModel/NoticeDetailResponse.swift
  UniVoice/UniVoice/Data/DTO/ResponseModel/QuickScanStoryResponse.swift
  UniVoice/UniVoice/Data/DTO/ResponseModel/SavedNoticeListResponse.swift
  UniVoice/UniVoice/Data/DTO/ResponseModel/UniversityDataResponse.swift
  UniVoice/UniVoice/Data/DTO/ResponseModel/UnreadQuickScanListResponse.swift
Labels: 🧹 Chore
